Repository LT-Students/DigitalOffice-FileService, pull requests merged in 2020-10, with the labels that each got.

#4 Fix cors url
  src/FileService/appsettings.json
Labels: bug

#3 Update xml comments
  src/FileService.Broker/FileService.Broker.csproj
  src/FileService.Business/AddNewFileCommand.cs
  src/FileService.Business/FileService.Business.csproj
  src/FileService.Business/GetFileByIdCommand.cs
  src/FileService.Business/Interfaces/IAddNewFileCommand.cs
  src/FileService.Business/Interfaces/IGetFileByIdCommand.cs
  src/FileService.Data.Provider.MsSql.EF/FileService.Data.Provider.MsSql.Ef.csproj
  src/FileService.Data.Provider/FileService.Data.Provider.csproj
  src/FileService.Data/FileRepository.cs
  src/FileService.Data/FileService.Data.csproj
  src/FileService.Mappers/FileService.Mappers.csproj
  src/FileService.Models.Db/FileService.Models.Db.csproj
  src/FileService.Models.Dto/FileService.Models.Dto.csproj
  src/FileService.Validation/FileService.Validation.csproj
  src/FileService/FileService.csproj
  test/FileService.Broker.UnitTests/FileService.Broker.UnitTests.csproj
  test/FileService.Business.UnitTests/AddNewFileCommandTests.cs
  test/FileService.Business.UnitTests/FileService.Business.UnitTests.csproj
  test/FileService.Data.UnitTests/FileService.Data.UnitTests.csproj
  test/FileService.Data.UnitTests/GetFileByIdRepositoryTests.cs
  test/FileService.Mappers.UnitTests/FileService.Mappers.UnitTests.csproj
  test/FileService.Validation.UnitTests/FileService.Validation.UnitTests.csproj
Labels: documentation

#5 DeleteFileById endpoint
  src/FileService.Broker/FileService.Broker.csproj
  src/FileService.Business/DisableFileByIdCommand.cs
  src/FileService.Business/FileService.Business.csproj
  src/FileService.Business/Interfaces/IDisableFileByIdCommand.cs
  src/FileService.Data/FileRepository.cs
  src/FileService.Data/Interfaces/IFileRepository.cs
  src/FileService/Controllers/FileController.cs
  src/FileService/FileService.csproj
  src/FileService/Startup.cs
  test/FileService.Business.UnitTests/AddNewFileCommandTests.cs
  test/FileService.Business.UnitTests/DisableFileByIdCommandTests.cs
  test/FileService.Data.UnitTests/DisableFileByIdRepositoryTests.cs
Labels: enhancement

#6 Renamed layer to Models.Broker and updated packages
  LT.DigitalOffice.FileService.sln
  src/FileService.Broker/FileService.Broker.csproj
  src/FileService.Data.Provider.MsSql.EF/FileService.Data.Provider.MsSql.Ef.csproj
  src/FileService.Data.Provider/FileService.Data.Provider.csproj
  src/FileService.Models.Broker/FileService.Models.Broker.csproj
  src/FileService.Models.Broker/Requests/IGetFileRequest.cs
  src/FileService.Models.Broker/Responses/IFileResponse.cs
  src/FileService/FileService.csproj
  test/FileService.Broker.UnitTests/FileService.Broker.UnitTests.csproj
  test/FileService.Business.UnitTests/AddNewFileCommandTests.cs
  test/FileService.Business.UnitTests/FileService.Business.UnitTests.csproj
  test/FileService.Data.UnitTests/FileService.Data.UnitTests.csproj
  test/FileService.Mappers.UnitTests/FileService.Mappers.UnitTests.csproj
  test/FileService.Validation.UnitTests/FileService.Validation.UnitTests.csproj
Labels: enhancement
